spring.application.name=ecom-backend
# URL de l'UI Swagger : http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
# Affiche les BigDecimal avec 2 décimales : 1199.00 et non 1199
spring.jackson.serialization.write-bigdecimal-as-plain=true
